export const ADMIN_ROUTE = '/admin'
export const LOGIN_ROUTE = '/login'
export const REGISTRATION_ROUTE = '/registration'
export const MAIN_PAGE_ROUTE = '/'
export const FORUM_ROUTE = '/forum'
export const FAQ_ROUTE = '/faq'
export const PERSONAL_PAGE_ROUTE = '/personal'
